### ISSUE TITLE
Fixed problems with pressure and total rain

### ISSUE THREAD

**Issue by SDRU** [shaneHowearth/Dream-Link-WH1080-Weather-Station#1]
Hi Shane,
thanks a lot for the code!
It will calculate the pressure and total rain if you change:
total_rain = struct.unpack('H', current_block[13:15])[0]*0.3
abs_pressure = struct.unpack('H', current_block[7:9])[0]*0.1

**Comment by shaneHowearth** [comment]
Thanks for spotting this! I'm not sure what to do now, do you have a repository you would like to issue a pull request from?

**Comment by SDRU** [comment]
Hi Shane, 
no I don't have a repository. These two lines were the only problem that I found.
Sandra

**Comment by shaneHowearth** [comment]
Hi Sandra
The fix you've found is significant, and although I could apply the fix myself, I would prefer that you got the credit, and that would happen through the PR system.

See if this helps https://help.github.com/articles/creating-a-pull-request/ Create a PR for me and I will merge it.

**Comment by SDRU** [comment]
Hi Shane,
first I need to learn again how to work with git! Afterwards I will upload my code. It also saves all data to a csv file.

**Comment by SDRU** [comment]
I hope it works!
